### ISSUE TITLE
arki-scan --dispatch: too many open files

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#103]
When importing a file with records extending across a number of steps greater than `ulimit -n`, `arki-scan` doesn't import the data correctly, because the process has too many open files.

Here, an example with a `iseg` dataset (format `vm2` and daily step), but I found the same problem with `iseg` dataset (`bufr` format) and with `ondisk2` dataset.

```
$ mkdir -p issue/dataset/{error,vm2_daily_iseg}
$ cat > issue/dataset/error/config <<EOF
step = daily
type = error
EOF
$ cat > issue/dataset/vm2_daily_iseg/config <<EOF
filter = area:VM2,
replace = yes
step = daily
type = iseg
format = vm2
smallfiles = yes
unique = reftime, area, product
index = reftime, area, product
EOF
$ arki-mergeconf issue/dataset/* > issue/config
$ for i in $(seq $(( $(ulimit -n) +1 )) ); do echo "$(date -ud @$(( i * 86400 )) +%Y%m%d%H%M),1,158,23,,,"  ; done > issue/in.vm2
$ arki-scan --dispatch=issue/config --dump issue/in.vm2 &> issue/vm2_daily_iseg.log
$ tail -n11 issue/vm2_daily_iseg.log
Source: BLOB(vm2,/autofs/nethomes/edigiacomo/tmp/issue/in.vm2:25600+24)
Product: VM2(158, bcode=B12101, l1=2000, lt1=103, p1=0, p2=0, tr=254, unit=C)
Reftime: 1972-10-22T00:00:00Z
Area: VM2(1,lat=4460016, lon=1207738, rep=locali)
Value: 23,,,
Note: 
 [2017-09-14T10:38:51Z]Scanned from /autofs/nethomes/edigiacomo/tmp/issue/in.vm2
 [2017-09-14T10:38:51Z]Failed to store in dataset 'vm2_daily_iseg': cannot execute replace query: unable to open database file
 [2017-09-14T10:38:51Z]Failed to store in dataset 'error': cannot open file /autofs/nethomes/edigiacomo/tmp/issue/dataset/error/1972/10-22.vm2: Too many open files
 [2017-09-14T10:38:51Z]WARNING: The data has not been imported in ANY dataset
$ arki-query --summary --summary-restrict=reftime --dump '' issue/dataset/* | grep Count
  Count: 1004
$ ulimit -n
1024
...

**Comment by spanezz** [comment]
I have identified the issue at `arki/runtime.cc:617`: it keeps in memory all imported metadata for the file being processed. Imported metadata hold a lock to the file which contains their data, so that it won't get repacked while they exist, and they are always able to retrieve the data they describe from disk.

However, when an input file would dispatch to more than `ulimit -n` segments, given that to hold a lock one needs to hold an open file descriptor to the file, we hit this bug.

The solution is to refactor the process not to keep all metadata for an imported file in memory. Alternatively, to unlock the blob data sources on the imported metadata, and either document that retrieving data from metadata coming out of arki-scan is not supported (so, making `arki-scan --inline` or `arki-scan --data` conflict with `arki-scan --dispatch`), or perhaps it's enough to safely drop the locks as long as the datataset itself is still open for writing, since it will also have a dataset-wide lock.

For today I stop at documenting where the problem is. Next week I can pick it up from here and work at fixing it.

**Comment by spanezz** [comment]
Intermediate results pushed to branch `issue103`

**Comment by spanezz** [comment]
I reproduced the bug also querying a dataset, where the query results are in more segments than open files limit.
It seems I need to drop having the metadata lock its data file during its lifetime. I'll now look at options

**Comment by edigiacomo** [comment]
> do we need arki-scan --data or --inline? (we probably should/could use --move* --copy* options)

Mai usati, per me si possono segare allegramente.

> granularità dell'ordinamento dell'arki-query: è possibile limitare l'ordinamento al passo del segmento per non dover tener lockati più di un segmento alla volta durante la query?

Personalmente, non mi è mai capitato di fare query che abbiano come criterio principale di ordinamento qualcosa di diverso dal reftime, quindi benissimo.

> pompare ulimit per gli arki server potrebbe comunque essere opzione legittima

Sì, ci può stare.
