### ISSUE TITLE
arki-check di un singolo segmento su dataset iseg

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#109]
Il check completo di un dataset `iseg` comporta il check di ogni suo segmento. Tuttavia, questo significa che - almeno nei nostri casi d'uso - il check perde molto tempo analizzando segmenti su cui non deve fare nulla.

Questo, insieme a #108, rende praticamente inutilizzabile il dataset `iseg`.

Inoltre, nei casi (infrequenti ma non rari) in cui elimino l'indice. la rigenerazione dello stesso (e quindi la disponibilità dei dati) può richiedere molto tempo di attesa.

Invece che implementare ottimizzazioni particolari su `arki-check`, mi chiedevo se non fosse possibile - vista la natura autoconsistente del segmento - permettere il check e il repack di un singolo segmento.

**Comment by spanezz** [comment]
I started working on this: refactoring on #108 made it much easier to implement.

Is checking of iseg datasets significantly slower than checking on simple or ondisk2 datasets, or is this feature request just an idea for indeed exploiting the locality of changes to avoid checking and rechecking segments that are never changed anyway?

**Comment by spanezz** [comment]
Note that although it looks like `arki-check --remove-all --filter=reftime:<2016` is a valid and tempting invocation, currently `--filter` will match *at least* the segments specified, and possibly more, like, the entire dataset. So that command currently removes all the contents of the dataset.

`--filter` is currently only implemented for `--state`, `--repack` and the default check mode, and only for `iseg` datasets.

I can implement it for all the other datasets, and also for `--remove-all`, but for now I wanted to at least push what can satisfy the requirement in this issue. I'm opening a new issue for extending `--filter` to cover the rest of the cases

**Comment by edigiacomo** [comment]
Thanks, Enrico!

> Is checking of iseg datasets significantly slower than checking on simple or ondisk2 datasets, or is this feature request just an idea for indeed exploiting the locality of changes to avoid checking and rechecking segments that are never changed anyway?

The latter.
