### ISSUE TITLE
`cleps_pf16_HighPriority.grib2` behaviour changed with eccodes

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#121]
Hello,

I have successfully built arkimet with eccodes, and all tests succeed except one.

Something changed between grib_api and eccodes with regards to the handling of `
test/data/cleps_pf16_HighPriority.grib2`: where the level scanned from that file used to be `GRIB2S(001, -, -)`, now it is scanned as `GRIB2S(001,   -, 2147483647)`.

I suspect the problem may be more in the test file itself than in the library behaviour, and I would like to double check with you the validity of that example grib.

Can you please compare a grib_dump of that file done with grib_api and with eccodes, and let me know if the file is still relevant, and if yes, how arkimet is supposed to scan it?

For reference the scanning code is at `conf/scan-grib2/01-common.lua`, currently at line 39 and directly above.

**Comment by dcesari** [comment]
I checked a grib_dump with grib_api and eccodes (quite an old verdion actually 2.4.2 of last summer) and I do not notice differences, both report:
```
23        typeOfFirstFixedSurface = 1 [Ground or water surface  (grib2/tables/5/4.5.table) ]
24        scaleFactorOfFirstFixedSurface = MISSING
25-28     scaledValueOfFirstFixedSurface = MISSING
29        typeOfSecondFixedSurface = 255 [Missing (grib2/tables/5/4.5.table) ]
30        scaleFactorOfSecondFixedSurface = MISSING
31-34     scaledValueOfSecondFixedSurface = MISSING
```
which is the desired content (to answer the question "is the example still relevant?"). I cannot convince any grib_* tool to print the raw value for scaleFactor... and scaledValue..., only "MISSING", but I assume it is the usual value with all bits set to 1. My bet is that the behavior changes in the line
```
	if gribl.scaleFactorOfFirstFixedSurface ~= -1 then
```
i.e. the test is true even with scalFactor missing and then lvalue1 is set explicitly to the grib missing value. Maybe something changes in the interface to grib_api/eccodes in relation to signed/unsigned -1/255?
Actually I cannot deduce from WMO manual (page 59-60 of https://library.wmo.int/opac/doc_num.php?explnum_id=3421) whether scaleFactor can be negative or not.

**Comment by amontani** [comment]
I have just performed grib_dump at ECMWF, where I used either grib_api 1.17.0 or ecCodes 2.5.0 .
The results of the grib_dump commands are the same (attached).
[compare_cleps.zip](https://github.com/ARPA-SIMC/arkimet/files/1672961/compare_cleps.zip)
Hope this helps.

**Comment by edigiacomo** [comment]
In eccodes (2.6.0):
```
#define GRIB_MISSING_LONG 2147483647
```

In gribapi:
```
#define GRIB_MISSING_LONG 0xffffffff
```

**Comment by edigiacomo** [comment]
Moreover:
Moreover, in `arki/types/level.cc`:

```
const uint32_t GRIB2S::MISSING_VALUE = 0xffffffff;
```

**Comment by dcesari** [comment]
After some brainstorming with @edigiacomo we concluded that:
1. `if gribl.scaleFactorOfFirstFixedSurface ~= -1 then` is ALWAYS true even when gribl.scaleFactorOfFirstFixedSurface is missing since grib_api seems to reset the native grib missing value with a long missing value 0xffffffff=4294967295 also for 1-octet keys, so the following code
```
			lscale2 = grib.scaleFactorOfSecondFixedSurface
                        lvalue2 = grib.scaledValueOfSecondFixedSurface
```
is always executed also in case of missing numerical level, after that the function
```
static std::unique_ptr<Level> createGRIB2S(uint8_t type, uint8_t scale, uint32_t val);
```
sets correctly the missing values also for the 8 bit case, but

2. on eccodes the missing value returned becomes 0x7fffffff=2147483647 which does not have all the bits to 1 and that is probably still cast to a missing value for the 8 bit key (8 bits set to 1) but not for the 32 bit key.

**Comment by edigiacomo** [comment]
With gribapi `lvalue1` is `-` because `GRIB_MISSING_LONG == 0xffffffff == GRIB2S::MISSING_VALUE`, but with eccodes `lvalue1` is `2147483647` because `(GRIB_MISSING_LONG == 2147483647) != (GRIB2S::MISSING_VALUE == 0xffffffff)`.

`lscale1` is  `-` with both the libraries because is a `uint8_t` (see https://github.com/ARPA-SIMC/arkimet/blob/master/arki/types/level.cc#L800).

See https://github.com/ARPA-SIMC/arkimet/blob/master/arki/types/level.cc#L664-L685 and https://github.com/ARPA-SIMC/arkimet/blob/master/arki/types/level.cc#L800.

In addition, am I wrong (I hope) or is a full rescan of the GRIB archives needed?

**Comment by spanezz** [comment]
A quick fix to support both libraries could be this, since all object creation goes via GRIB2S::create:
```
--- a/arki/types/level.cc
+++ b/arki/types/level.cc
@@ -802,7 +802,7 @@ unique_ptr<GRIB2S> GRIB2S::create(unsigned char type, unsigned char scale, unsig
     GRIB2S* res = new GRIB2S;
     res->m_type = type;
     res->m_scale = scale;
-    res->m_value = value;
+    res->m_value = value == 0x7fffffff ? MISSING_VALUE : value;
     return unique_ptr<GRIB2S>(res);
 }
```
Would that work?

**Comment by spanezz** [comment]
Alternatively, I do that comparison only when printing the string, and keep in the level the exact values that were in the grib file

**Comment by dcesari** [comment]
That should work. Maybe a portable alternative could be to use upstream (don't know exactly where) the grib_is_missing function (see https://software.ecmwf.int/wiki/display/GRIB/grib_api.h+File+Reference) to test a key?! That approach should overcome the eccodes/grib_api incompatibilities.

**Comment by edigiacomo** [comment]
> Alternatively, I do that comparison only when printing the string, and keep in the level the exact values that were in the grib file

Maybe I am missing something, but I think that there's a problem when saving the level value in the metadata index too: if you don't normalize the value of `m_value`, arkimet could save different level values depending on the library used.

The quick fix is ok for me, but maybe this is more readable?

```
res->m_value = value == GRIB_MISSING_LONG ? MISSING_VALUE : value;
```

**Comment by spanezz** [comment]
Works for me, defaulting on `res->m_value = value` if grib_api is not available during build.
