### ISSUE TITLE
web service broken at "Perform a query"

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#144]
http://myserver:8090/
click on  "Perform a query" and my browser download about  800Mb of something .
The expected behaviour is the possibility to specify a query.

**Comment by brancomat** [comment]
Just for the record, this bug seems still presenti in the current version (1.25)

**Comment by brancomat** [comment]
Still present in 1.29

**Comment by spanezz** [comment]
A long time a go, in a version far far away, "Perform a query" linked to a form where one could paste an arkimet query and download its results. The form has long since disappeared, and only the link remained.

arki-server also didn't make a distinction between GET and POST queries, so clicking on the link would cause the same result as querying all datasets without arguments.

I have now removed the link, and added a distrinction between GET and POST in arki-server, so get inadvertedly GET-ting a query link will return "405 Method not allowed" instead of performing a huge query.

This technically fixes the problem, assuming that the old form is not needed, and that the way to access arki-server is via arki-query.

If there is a real use case for querying arki-server via browser instead, let's map it into a new issue, then add/readd support for it.
