### ISSUE TITLE
are `--moveko` and `---copyko` options tested with a cross-device copy in the test suite?

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#146]
We hit a bug in an old arkimet version (`1.6-3`): the moveko option failed with this error:
`Invalid cross-device link`

I still have to test this on current master, but the real question is: is the cross-device copy tested in the test suite?
If it isn't tested, I think it should be: the 90% use case of those options is a cross-device situation in a crisis scenario (when the data can't be imported) so it's the kind of thing that you notice it's not working when it's too late.

**Comment by spanezz** [comment]
`--copy*` should work cross-device: none of what it does depends on device boundaries.

`--move*` is not tested cross-device because it is not supported as a cross-device operation. It is implemented with a simple rename, which is a much more robust operation than a copy, and I would strongly prefer to keep it that way.

I intended `--moveok`/`--moveko` to be used in a situation such as a spool directory like this:
```
/spool/incoming
/spool/ok
/spool/failed
```
scripted so that all files in `incoming/` are processed, and arkimet moves them to `ok/` and `failed/` depending on their outcome.

What is your situation?

**Comment by brancomat** [comment]
> What is your situation?

Diverse. Depending on implementation syle (and programmer), historical period, file size (that sometimes deter recourse to a spool directory) the currently running procedures might use a different range of approaches.

Let's say that usually:
- incoming files are on nfs paths or remote sources (ftp, scp)
- the single procedure could copy the source file in its temporary workdir but in some nfs cases the dispatch could be done on the fly
- we don't keep "ok" files
- we keep "ko" files in a different path if the source file is to be deleted (that's not always the case)

That's not written in stone, it could be a good idea to set some best practice on this (chiming in @edigiacomo, @dcesari @pat1 for contributions)

Anyway, in a number of procedures we're using `--move-ko` to save ko data (to destination paths in separate devices) and as a first step I'd say we should change it to a `--copy-ko` with subsequent removal of the source file.

The fact that `--move*` options are not supported as cross-device operations it's not a problem per se (since we have the `--copy*`) but I think it should be mentioned somehow in the man page (I haven't updated `arki/runtime/dispatch.cc` myself because I still can't find a clear wording to put it)
