### ISSUE TITLE
memory issues in arkimet 1.7-5 (fedora 24)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#152]
`arki-scan --dispatch` of a 12Gb grib file fills up 8Gb of RAM (and get killed by oom-killer before ending)

the same file with arkimet 1.4-3 uses a negligible amount of ram

I'm gathering other informations on this issue and creating a test case somewhere before switching the assignee to @spanezz

**Comment by brancomat** [comment]
steps to reproduce, on:
`makerpm@ventiquattro:/homelocal/makerpm/arkiissue152`

```bash
 arki-scan --yaml --dispatch=./arkiconf /autofs/scratch2/dbranchini/cosmovol/cosmo_5M_vol_ita.2018092700.grib
```

I launched it inside a `/usr/bin/time -v` and killed when it reached almost 40% of ram (see "Maximum resident set size"):
```bash
[makerpm@ventiquattro arkiissue152]$ /usr/bin/time -v arki-scan --yaml --dispatch=./arkiconf /autofs/scratch2/dbranchini/cosmovol/cosmo_5M_vol_ita.2018092700.grib
^CCommand terminated by signal 2
	Command being timed: "arki-scan --yaml --dispatch=./arkiconf /autofs/scratch2/dbranchini/cosmovol/cosmo_5M_vol_ita.2018092700.grib"
	User time (seconds): 34.03
	System time (seconds): 9.34
	Percent of CPU this job got: 24%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:55.29
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1853228
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 1647314
	Voluntary context switches: 50273
	Involuntary context switches: 52279
	Swaps: 0
	File system inputs: 27203576
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by brancomat** [comment]
here's the output of valgrind, apparently no warnings before the out of memory error:
[valgrind.txt](https://github.com/ARPA-SIMC/arkimet/files/2424453/valgrind.txt)

**Comment by edigiacomo** [comment]
I think I've found the issue: if I'm correct (and I wouldn't bet), [the dispatcher iterates over the list of the metadata][1] (one for each GRIB file) and in this loop [it reads the data][2], but the data are never released:

I run `arki-scan` with `gdb` and a breakpoint after the end of the loop shows that each metadata in the list will keep its data in memory.

I cannot ispect the `batch` vector because is optimized by compiler, but the `WriterBatchElement` objects outlive the loop and I can inspect them after some lines:

```
(gdb) b arki/dispatcher.cc:168
Breakpoint 1 at 0x7ffff7af063d: file dispatcher.cc, line 168.
(gdb) r --dispatch=dataset.conf --dump test/data/test.grib1
Breakpoint 1, arki::Dispatcher::dispatch(arki::dataset::WriterBatch&) () at dispatcher.cc:170
170         for (auto& b: by_dataset)
(gdb) n
172             raw_dispatch_dataset(b.first, b.second);
(gdb) p b.second.at(0)->md.m_data.size()
$1 = 34960
```

[1]: https://github.com/ARPA-SIMC/arkimet/blob/v1.7-5/arki/dispatcher.cc#L80
[2]: https://github.com/ARPA-SIMC/arkimet/blob/v1.7-5/arki/dispatcher.cc#L80

**Comment by edigiacomo** [comment]
I tried with a very quick and dirty patch (see attachment) and the difference of "maximux resident set size" between the two versions is more or less the dimension of the file scanned.

[issue-152.patch.txt](https://github.com/ARPA-SIMC/arkimet/files/2427849/issue-152.patch.txt)

**Comment by spanezz** [comment]
At a quick glance, that patch seems like the way to go for me

**Comment by edigiacomo** [comment]
Good! I write a version using a RAII approach to avoid code duplication.

**Comment by spanezz** [comment]
I studied the situation a bit more.

The expected situation is that arki-scan --dispatch of a 12Gb grib file would load the 12Gb grib file into ram. 

The reason is that I need to read all the GRIB data in input, to scan their contents, and then I need to write it all in the datasets, so I might as well keep the data I read in RAM, to avoid reading them twice.

That approach seems to have become insufficient. Tell me more about that 12Gb GRIB file: is it expected to be this big? Does it contain few very large GRIB items, or lots and lots of small GRIBs?

I don't want to fix this and double the I/O for all import operations, if I can avoid it, and I'd like to study the updated requirements to figure out a solution that minimizes I/O and limits memory usage.

**Comment by spanezz** [comment]
I summarise this morning's confcall.

The 12Gb GRIB is a file containing thousands of different GRIB elements, each in the order of 100Kb long.

A possible way of importing it is to scan it in chunks: while scanning it, if the size of the data scanned so far is bigger than a given amount, the data read so far is imported and removed from RAM, and so on.

Another interesting option is not to store data into memory, but to mmap the input files, or use a system call like `copy_file_range(2)` to shift data from source to destination without requiring to have it in memory.

If the input is imported piecemeal, there is the question of what happens if one piece fails to import. I will be adding unit tests to check what is the current transactional behaviour when importing batches of data, to be able to reason on this.

**Comment by spanezz** [comment]
I investigate what happens if one piece fails to import. Currently, arki-scan quits with an error. I fixed it (in the branch `issue151`) so that it handles the error and continues processing the rest.

In case of an error, all data that would end up in the same segment fails to import, even if only one item in a large batch was the cause of errors. This is because imports are batched together for speed, and one error causes the failure and rollback of the whole segment-based transaction.

**Comment by spanezz** [comment]
I merged to master a mitigation for the memory usage. Now once a batch has been imported, and optionally also copied to `--copyok`/`--copyok`, the data cached in RAM for that batch is dropped.

It should not make much difference, because all the data is still read in RAM at scan time, but it does contain important refactorings that I want to release

**Comment by spanezz** [comment]
This should be enough to address the memory issues, I'm adding the review tag.

The situation could still be improved now that I have a better abstraction layer for cached data, and I could for example not cache data in RAM at all, but use functions like `copy_file_range` to move data directly from the input file to the dataset without allocating userspace memory. This would be en extra enhancement, and I expect that with the data currently being processed, the `--flush-threshold` feature should solve the memory issue.

**Comment by brancomat** [comment]
Great! I'll make a new release shortly. (I'll bump arkimet version to 1.8 since it's a big change in data handling and performance impact)

**Comment by brancomat** [comment]
So far, no more memory issue.
