### ISSUE TITLE
Filtering by bounding box bufr datasets

### ISSUE THREAD

**Issue by bchiavarini** [ARPA-SIMC/arkimet#223]
Hi,
I have a dataset of observed data in bufr format and i have to filter it by area to check if there are data available for a given bounding box.
I have tested the example of query for area given in the matcher documentation on one of my datasets of forecast data and it works:
query:
`arki-query --json --summary-short --annotate 'area: bbox intersects LINESTRING(11.3 44.4, 11.3 44.5, 11.3 44.5, 11.3 44.4, 11.3 44.4)' /arkimet/datasets/vlm5`

bounding param for this dataset given by `arki-mergeconf --extra`:
```
bounding = POLYGON ((-17.5374014843514558 25.8214118125177627, -29.6618577019240988 49.1185603319763260, -18.1123487722656762 52.2082915170863942, -5.2841914142956252 54.2586288297216370, 8.3858281354571460 55.0739215029660087, 22.1519686504923001 54.5643432849449539, 35.2289961673372574 52.7869189178025664, 47.0956192803686022 49.9188746081732049, 47.1122744703592744 49.8885465483880779, 35.6138690063754808 26.3910672255853775, -17.5374014843514558 25.8214118125177627))
```
example of an area in this dataset:
`GRIB(Ni=1083, Nj=559, latfirst=-13028000, latlast=12083000, latp=-47000000, lonfirst=-25290000, lonlast=23400000, lonp=10000000, rot=0, type=10)`

But the same query does not give any result in a dataset of bufr files.

bounding param for this dataset given by `arki-mergeconf --extra`:
```
POLYGON ((12.5735399999999995 44.0591900000000010, 10.6491699999999998 44.1793400000000034, 10.4657999999999998 44.2471600000000009, 10.6336999999999993 44.6978099999999969, 12.2741699999999998 44.7978999999999985, 12.5735399999999995 44.0591900000000010))
```
example of an area in this dataset:
`"s":"GRIB","va":{"lat":4424716,"lon":1046580}}`

I understand that the issue depends on the way the area is described, so i am wondering if there is a way to filter by bounding boxes also datasets in bufr format.
Thanks for your help!

**Comment by edigiacomo** [comment]
The difference is that a GRIB message covers an _area_ (it's a grib), while a BUFR message is a _point_ (it's a weather station). This means that if you query a GRIB dataset using `area: bbox intersects LINESTRING(...)` , you will find alle the GRIB messages whose area intersects the given line. But if you query a BUFR dataset, you will find all the messages whose point intersects the given line.

E.g. only the BUFR messages with longitude 11.3 and latitude between 44.4 and 44.5 will match the query `LINESTRING(11.3 44.4, 11.3 44.5, 11.3 44.5, 11.3 44.4, 11.3 44.4)`.

Then, you must use a `POLYGON` to query a BUFR dataset, e.g. `bbox intersects POLYGON(...)` or `bbox coveredby POLYGON(...)`.

Note 1: the bounding box of a dataset can trick you because it gives you a [convex hull](https://en.wikipedia.org/wiki/Convex_hull) of the dataset and then it's very likely that a query using a linestring will return an empty result: for example, a dataset with four BUFR messages will have a bounding box whose vertex are the four BUFR messages.

Note 2: the `bbox` refers to the geographic description of the single record, whereas the bounding box of the dataset is the overall bounding box of all the data in the dataset.

**Comment by bchiavarini** [comment]
I have tried with the same query using polygon instead of linestring 
` arki-query --json --summary-short --annotate 'area: bbox intersects POLYGON((11.30939 44.47985, 11.30939 44.51291, 11.36158 44.51291, 11.36158 44.47985, 11.30939 44.47985));' /arkimet/datasets/opendata-er`
but it still doesn't give me any result, even if i know that the area described in the query i am testing contains some weather stations whose data are in this dataset

**Comment by edigiacomo** [comment]
Could you please

* Extract a single BUFR message from the dataset
* Execute the arki-query against it ( `arki-query ... data.bufr > out.bufr` treats the file `data.bufr` as it was a dataset ) with `--verbose` and `--debug` options
* Paste here the command, the log of the command and the size of the output file
* Attach here the input file

Thank you!

**Comment by bchiavarini** [comment]
command:
`arki-query --data --verbose --debug 'area: bbox intersects POLYGON((11.30939 44.47985, 11.30939 44.51291, 11.36158 44.51291, 11.36158 44.47985, 11.30939 44.47985));' /data/single_extraction.bufr > /data/out.bufr`

log:
INFO Processing /data/single_extraction.bufr...

/data/out.bufr has size 0

input file:
[single_extraction.zip](https://github.com/ARPA-SIMC/arkimet/files/4427632/single_extraction.zip)

**Comment by edigiacomo** [comment]
```
arki-mergeconf --extra single_extraction.bufr
[single_extraction.bufr]
bounding = POINT (12.5735399999999995 44.0591900000000010)
format = bufr
name = single_extraction.bufr
path = /home/edg/Downloads/single_extraction.bufr
type = file
```


This is a screenshot of the bounding box of the query (top left) and the BUFR (bottom right)

![image](https://user-images.githubusercontent.com/927277/78368749-62cf1600-75c4-11ea-9ad8-72b809e5223d.png)

The polygon is located in Bologna and the BUFR in Rimini.

**Comment by bchiavarini** [comment]
i have tried with a wider area 
` arki-query --data --verbose --debug 'area: bbox intersects POLYGON((10.28 44.93,10.28 44.11, 12.73 44.11, 12.73 44.93, 10.28 44.93)) ;' /data/single_extraction.bufr > /data/out.bufr`

still out.bufr is empty

**Comment by edigiacomo** [comment]
You are almost there :)

![image](https://user-images.githubusercontent.com/927277/78369506-952d4300-75c5-11ea-95c5-daa158b54214.png)

**Comment by bchiavarini** [comment]
I have tried with a correct bounding box and now it works.
I have checked, and the first time (with the dataset) it hasn't worked because moving the data from dballe to arkimet a lot went in error and the data i expected coming from the stations in the bounding box have been "lost" during this operation.
Thank you very much for your patience and sorry for the bother!

**Comment by edigiacomo** [comment]
No bother at all, glad to help!
