### ISSUE TITLE
memory problem with arki-check -f -r  on bufr

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#242]
using bufr on segment of about 2Gbyte running 
arki-check -f -r 
take this amount of memory
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                
2380068 root      20   0   18,9g  14,6g    932 D   8,3  94,4 116:30.85 arki-check
```
on a machine with 16G ram and 8G swap the memory is exhausted
 
here test data to replicate the problem:
```
https://drive.google.com/drive/folders/1eOFGADREjkt_a40d6j7OT9Y4re6kI7mi?usp=sharing
```

**Comment by spanezz** [comment]
I replicated the issue like this:
```
mkdir ds
cp config ds/
mkdir ds/2020
cp 10.bufr ds/2020/
arki-check -f ds
```

I'll now investigate

**Comment by spanezz** [comment]
I checked, and the scan is not holding in memory all the *data*. It must however hold in memory all the metadata.

That BUFR segment contains 15'582'372 BUFRs. It's hard to estimate how much memory one metadata needs, but it could be between 500b and 1k, given various data structures and 64bit pointers for polimorphism (each metadata comes in various flavours), plus full pathname to the file, and so on.

I can try to compute that more accurately. However, if we do a back-of-the-envelope assumption at 750b, we get 15'582'372 * 750 = 11'686'779'000 and we're already at around 11Gb of RAM needed to hold all metadata in memory.

It's worth planning work to reduce that, definitely, but it's not the kind of thing that I can do quickly. Meanwhile, I'd recommend switching to `step=daily` instead of `step=monthly` for that kind of segment.

Note that since this seems to be about the size of *metadata* rather than the size of *data*, a multi-gigabyte GRIB segment wouldn't show this issue, since the GRIB data is several orders of magnitude bigger than its arkimet metadata.

**Comment by spanezz** [comment]
I've opened #245 about exploring a possibility of reducing memory usage of metadata, and measuring performance differences in the two approaches.

**Comment by pat1** [comment]
ok, I switch to step=daily configuration

**Comment by pat1** [comment]
mmm, come si fa a migrare un dataset da  step=monthly a step=daily ?
ho provato a cambiarlo nella conf ed eseguire un arki-check, ma senza successo.
Devo ricreare tutto compreso i segmenti in .archive ?

**Comment by spanezz** [comment]
Sí, l'unica per cambiare step al momento è reimportare
