### ISSUE TITLE
arki-check documentation

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#88]
`arki-check` lacks a puntual description of what it does. The manpage says that "perform a maintenance run" but this should be expanded, with special attention to the standard check and the action performed with the repack option.

For example we found out that an `arki-check -f` seems to check all the `.archive` content, and it's not very clear how it discriminates the "outdated summaries and indices".

(Now, this is relative to what it actually does. There's another internal discussion on what it _should_ do, but I'll open a different issue for that)

**Comment by brancomat** [comment]
Adding production blocking since cosmo_5M repacks are taking too long because of strange "contains deleted data or data to be reordered" warnings

**Comment by spanezz** [comment]
I started documenting datasets, segments, checks, fixes and repacks with markdown files under `doc/`.

Can you have a look in branch issue88 and tell me if documentation like that would help?

For example: https://github.com/ARPA-SIMC/arkimet/blob/issue88/doc/ds-simple.md

**Comment by spanezz** [comment]
Because there are a lot of commonalities between datasets, I'm using [jinja2](http://jinja.pocoo.org/) templates to share common parts of markdown, and I added a simple `doc/update` script to render the markdown files from the templates.
I added the generated markdown files both to the repository and to the tarball, so python3-jinja2 is still not a requirement for building arkimet. The makefiles will still automatically regenerate the `.md` files from the `.md.j2` files if needed.
Having the generated `.md` files added to the repo means that the documentation is also fully browsable online on GitHub

**Comment by brancomat** [comment]
Ok, the documentation is great!
I still think that arki-check manpage could be more specific, but an explicit mention to the rest of the documentation will do.

The fact that `python3-jinja2` is not a requirement is good to hear, but I see it's available on official repos even for our old Fedora 20 servers, if it's not an issue for @dcesari's CentOs server we could add it to the BuildRequires.

**Comment by dcesari** [comment]
It's not an issue as long as you use the %{python3_vers} rpm macro since python3 is smartly called python34 in CentOS.

**Comment by spanezz** [comment]
Ok, noted. I'll see how it evolves: I tend to be afraid that documentation disconnected from the code tends to go out of sync, so I have started turning all those points in the documentation into annotated unit tests, and generating the documentation automatically from them: https://github.com/ARPA-SIMC/arkimet/blob/issue88/arki/dataset/maintenance-test.cc#L34

**Comment by spanezz** [comment]
I've added markdown documentation in `doc/`, part of which autogenerated from unit tests. All the check/fix/repack behaviour documented there is verified by some unit test.

During the work I disccovered that simple datasets only reordered data by reference time during repack, instead of reference time and offset like the other datasets, which could be the cause of continuous repackings in archives if the sorting algorithm wasn't stable. I have now changed it to sort by reference time and offset, which should make the sorting stable no matter what algorithm is used.
