### ISSUE TITLE
`make check -C arki` successful when some tests fail too

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#93]
```
$ make check -C arki
....
15/4860 tests failed
Failed with result 0
```

I think the problem is here https://github.com/ARPA-SIMC/arkimet/blob/v1.2-1/arki/runtest#L119: with `!`, the exit status is the logical negation of the command (then, `$?` is `0` when the command fails). So, `arki/runtest` always exit with status 0.

**Comment by spanezz** [comment]
It's currently hard to stop the build in case of testcase errors, because some GRIB-related tests depend on local ARPA patches to grib_api definition files, which I do not have in my development system. Ideally I could skip the tests if the local patches are not present, but I currently cannot think of a reasonable way to detect them.

**Comment by edigiacomo** [comment]
Something like `./configure --enable-arpae-tests` to run (or even compile) the tests based on Arpae patches could work?

E.g.
```
AC_ARG_ENABLE([arpae_tests],
                               [AS_HELP_STRING([--enable-arpae-tests], [Enable Arpae tests]))

if test "x$enable_arpae_tests" = xyes
then
    AC_DEFINE([ARPAE_TESTS])
fi
```

**Comment by spanezz** [comment]
Good idea!
